# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160104164526 on 2016-02-11 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_value', models.CharField(max_length=10)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(default=' ', max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='./images')),
                ('question_text', models.CharField(default=' ', max_length=200)),
                ('choice_one', models.CharField(blank=True, choices=[('not beautiful', 'not beautiful'), ('not easy', 'not user friendly')], max_length=200)),
                ('choice_seven', models.CharField(blank=True, choices=[('very beautiful', 'very beautiful'), ('very easy', 'very user friendly')], max_length=200)),
                ('question_type', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anglo_b', models.CharField(blank=True, max_length=200, null=True)),
                ('anglo_uf', models.CharField(blank=True, max_length=200, null=True)),
                ('nordic_b', models.CharField(blank=True, max_length=200, null=True)),
                ('nordic_uf', models.CharField(blank=True, max_length=200, null=True)),
                ('german_b', models.CharField(blank=True, max_length=200, null=True)),
                ('german_uf', models.CharField(blank=True, max_length=200, null=True)),
                ('latin_b', models.CharField(blank=True, max_length=200, null=True)),
                ('latin_uf', models.CharField(blank=True, max_length=200, null=True)),
                ('asian_b', models.CharField(blank=True, max_length=200, null=True)),
                ('asian_uf', models.CharField(blank=True, max_length=200, null=True)),
                ('japanese_b', models.CharField(blank=True, max_length=200, null=True)),
                ('japanese_uf', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ManyToManyField(to='survey.Question'),
        ),
    ]
