# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160104164526 on 2016-02-10 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20160210_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='q1',
        ),
        migrations.DeleteModel(
            name='Submit',
        ),
    ]
