# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160104164526 on 2016-02-10 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20160210_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age', to='survey.Choice')),
                ('anglo_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anglo_b', to='survey.Choice')),
                ('anglo_uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anglo_uf', to='survey.Choice')),
                ('asian_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asian_b', to='survey.Choice')),
                ('asian_uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asian_uf', to='survey.Choice')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='survey.Choice')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='survey.Choice')),
                ('german_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='german_b', to='survey.Choice')),
                ('german_uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='german_uf', to='survey.Choice')),
                ('japanese_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_b', to='survey.Choice')),
                ('japanese_uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_uf', to='survey.Choice')),
                ('latin_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latin_b', to='survey.Choice')),
                ('latin_uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latin_uf', to='survey.Choice')),
                ('nordic_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nordic_b', to='survey.Choice')),
                ('nordic_uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nordic_uf', to='survey.Choice')),
            ],
        ),
    ]
