# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160104164526 on 2016-02-10 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20160210_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='age', to='survey.Choice'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='anglo_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anglo_b', to='survey.Choice'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='anglo_uf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anglo_uf', to='survey.Choice'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='asian_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asian_b', to='survey.Choice'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='asian_uf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asian_uf', to='survey.Choice'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='submit',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='survey.Choice'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='german_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='german_b', to='survey.Choice'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='german_uf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='german_uf', to='survey.Choice'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='japanese_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='japanese_b', to='survey.Choice'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='japanese_uf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='japanese_uf', to='survey.Choice'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='latin_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latin_b', to='survey.Choice'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='latin_uf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latin_uf', to='survey.Choice'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='nordic_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nordic_b', to='survey.Choice'),
        ),
        migrations.AlterField(
            model_name='submit',
            name='nordic_uf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nordic_uf', to='survey.Choice'),
        ),
    ]
